---
title: "assignment 2"
author: "Rohin Sri Kumar"
date: "02/01/2022"

output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gapminder)
library(plotly)

```

Question1
```{r (1)}
mydata <- read.csv("/Users/rohin/Desktop/NYRestaurantInspection2022.csv")
as_tibble(mydata)
```

```{r,1(a)}
mydata1 <- mydata %>% filter(BORO=="Queens", CUISINE.DESCRIPTION=="Pizza")

```


```{r,1(b)}
mydata1 %>% group_by(DBA) %>% summarize(count=n()) %>% arrange(desc(count)) %>% slice(1:5)
```


```{r, 1(c)}
mydata1%>%filter( DBA=="SUSANO'S PIZZERIA & RESTAURANT")%>%group_by(INSPECTION.DATE)%>% select(c(INSPECTION.DATE))%>%print(n=Inf)
```

Question2
```{r, 2(a)}
mydata2 <- read.delim("/Users/rohin/Desktop/gapminder_2007_gini.tsv")
mydata2 %>% ggplot() + geom_boxplot(aes(continent,gini,color=continent),outlier.colour="red", outlier.shape=16,outlier.size=3, notch=FALSE)+ggtitle("Gini Index in all continents")

ggplotly()
```

```{r, 2(b)}
mydata2%>% ggplot(aes(gini, lifeExp, color = continent,size=pop,label=country)) + geom_point() +ggtitle("life expectancy V gini index")+ facet_wrap(~continent)
ggplotly()
mydata2%>%group_by(continent)%>% summarize(minimum = min(gini, na.rm = TRUE), maximum = max(gini, na.rm = TRUE), mean = mean(gini, na.rm = TRUE))

```
#(2b) There is a clear correlation between life expectancy and gini index. From the plot we can see that countries with lower gini index have higher life expectancy rate and countries with higher gini index have lower life expectancy rate. 


Question 3
```{r,3}
gdp1 <- mutate(gapminder, gdp = pop*gdpPercap)
head(gdp1)
```
```{r}
usa_gdp <- gdp1%>%filter(country=="United States",year==2007)
gdp2<- mutate(gdp1, gdp_ratio = gdp/usa_gdp$gdp)
head(gdp2)
```

```{r}
gdp3 <- gdp2 %>% group_by(continent, year) %>% summarize(median = median(gdp_ratio))
gdp3 %>% ggplot(aes(year, median, color = continent)) + geom_point() + geom_line()+ggtitle("Median V GDP Ratio")
ggplotly()
```
